import { JWT } from "google-auth-library";

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const keyFile = {
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
}

console.log(keyFile)

export const serviceAccountAuth = new JWT(keyFile);
